server:
  port: 8080
  servlet:
    context-path: /vcs

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.23:3306/vacan?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: qixinbaotest
  jpa:
    open-in-view: false
  redis:
    database: 0
    host: localhost
    port: 6379
#    password:
    timeout: 10000
    jedis:
      pool:
        max-active: 30
        max-wait: 10000
        max-idle: 10
        min-idle: 5
  data:
    redis:
      repositories:
        enabled: false

pagehelper:
  helper-dialect: mysql
  params: countSql
  reasonable: true
  support-methods-arguments: true

mybatis:
  mapper-locations: classpath:mapperxml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 172.18.0.2:9876
  producer:
    group: vcs

oss:
  type: minio

minio:
  server: http://172.18.0.5:9000
  accesskey: ciFZi6RfXrKhO3mIrwcO
  secretkey: uB86AIf3qvzY8gLQryAf58i7Bh9LbeDzH8AnhEz5
  bucket: vacan

auth:
  token-timeout: 1800000 #30分
  reftoken-timeout: 28800000 # 8小时
  remtoken-timeout: 604800000 # 一周

log-path: /home/moexc/ramfs

alipay:
  serverUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: 9021000137690066
  privateKey: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQCgaSa7vmjtR4KyuYMNeZ3TfrSBQchhpZ6/M6vUrZ2OsHksDi8eyfcbxpyE/10/h3nb6PFhqBAEAsqC5tcudgyHjMO7tUVbVoQjnGX4hQyVVQLMGjtHABzOGDajdE6vF2S8bsWvwHSbsj2QHJIk7dBPzxn0yO6yJu0+/VwPO7F0EayxNlIuyhc7qnJoFAtZN92VbnP22Wl72mYt1wSSPTlDqCannbO8HQ+skrlZRMiJeRT1PkDiYU4+9TZwdc62uRj3Orj2ZT6OeohkMMKA3QwlKn84cb4UfVnDdj4Bu5rQpCYB8OnxY7XGQpplQxSq5OqdrrV9DvEaZmHi3vd8sNu1AgMBAAECggEBAIj5gUOr0jlbaPVoh8nH4ccpWMVPAOaw4B9w5feT0Qh5FN9TtVTbLREgxaKj1GJdMudfwE6djh9+qqKgr3pS/1v4DWOJ5JGcDPXDpSdTpW0WzG6wr5FvPSmXb4Cf3liQ50ooZNIwyuHwj7UxUHIMSGb997IYqgqiRtAU1LmFRYBQBJaiKHUVcb6cffX3FngCe9W9XLKJi8x24cBX7Jm+e/dwzuhPcQ4EsgdKA9lKj3BuBk7gtkOhANj+s3ecxAJrkabGvfETZhyhCf6ZSideqx7rJS/4CbMeAeE18/7Wcfpm2maGJU5T/YOOzdiPXxF0To1KGHwRaeqoxNail/NaOzkCgYEA2ARrVcebEpzZefYLO6QdRj3Ex8zuvwgAhJ/GRmQ1RbXhmFijB9z2Dciak9T17lYwaw/w781VBMo7SibuvKS3CXXK7dECpaXz7W/UjqqddkBpYY9xa9Qge9Wo7Vtcw4mB1s37T28Djh+1f0AJZ4t5YOdeS9KE1cdYtps0dFjnqXMCgYEAvhnrZ75NMBiy9Xz7JlpsUgvgJzgYutamE/z2dAvkFEfFxtEyPI63Bcm/dn+V0XxjJ+3aCtyQpO/+YiKIgjuCmHAm/btnx4XNV8+qoky5mreOh7q1T0N3M9ebbcbiXTm3um7QFYHUcwp8J9Hc0vf432d26b5BlQi7fpSRCeDZvDcCgYEAiaOXOJrshhmGwJ0zXxccyArHfX9oiDPzEI41adij0P0o90dS6cmyxemSBKvm36vvQehwXnt4toqc6IySBYT2U4LIgGtywlVRbXKZ/yVbG2PDQbSCUnBhGkZzUnmqS7UsE9A/VsenfkFaBfCpjV5jQolpnepPVV+leQS/kXqscV0CgYEAoWhmjQ5ygVznTjLRF+58vGki6InjzXgFSUFmjH+wJ1wNXFMxQWO3mK2E6HtJ3LWthzCYCtLd6X1wUyiZGWKn7wCCyrs9UZaVFHLZobZdfTVPSoVH/sX8x0LQ0LOmbZtdGWmPOkOi/A6x/ildQq+TWzSBLdQB4SWp9L72KxoEJZ8CgYEAh2X5fFk3jYXPaYXV2OTUearEWjJZPqeagGY6utLE/9QR79kDIvaHCOOMIA+1Ujtw9Ewsgw3UZXstyNuJjWfEgILmWx06qfTu2RbG7TM7Qt0JjZj+BFhdLQ1xv1+NVqTRc47bnnuQpsMZXae9RhzyFQvBuMAZe8g/sUKNSnmBLwA=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApwxjkwnFikuWP4ZXbGi4itaUye/2UkwTWwgkdeAx+iBQusb2uBXKqEne9MK1MzzuiLRXPhiodZZzqLf3cUIc9UAsXfmWERB0uTJsZH7GAYJv6aTlhfEYXaXUsZEzQiW/eT3J0eynrVfxl729aL+XHyOMOeGsBOIgOkHY2pSjAyUkG7OARuiUBQWrQQMtUGxDOOG3CsqeVI+nxCWMJWVqAV9G+wy464eDCC4kdrXegIft08PMx9udy6Hj866sWuKtHdtur4BEh6ZA634Mehv7lhqtyC6AzXst38Cw/a/nYg+K0EijjNhvA6pf6Td/3P5LE2SiuPUiz6H6EI6S9TduLQIDAQAB
  format: json
  charset: utf-8
  signType: RSA2
  notifyUrl: http://98hyrm.natappfree.cc/vcs/api/pay/async

bid:
  engine-server: http://localhost:8081/bid
  method-create: /api/trade
  result-accept-uri: http://localhost:8080/vcs/api/trade/result

order:
  pay-timeout: 15m

cron:
  order:
    timeout-scan: 0 0/1 * * * ?